ï»¿spring.application.name=ms-security
spring.config.import=optional:file:.env[.properties]

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ms-security
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

server.port=5050

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5050/api/public/oauth2/callback/google

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email,read:user
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:5050/api/public/oauth2/callback/github

spring.security.oauth2.client.registration.microsoft.client-id=${MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.microsoft.client-secret=${MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.registration.microsoft.redirect-uri=http://localhost:5050/api/public/oauth2/callback/microsoft
spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-name-attribute=sub

app.frontend.url=${FRONTEND_URL:http://localhost:4200}

recaptcha.site-key=${RECAPTCHA_SITE_KEY}
recaptcha.secret=${RECAPTCHA_SECRET}
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
recaptcha.threshold=0.5

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM:${EMAIL_USER}}

app.2fa.expiration-minutes=5
app.2fa.max-attempts=3

app.password-reset.expiration-minutes=30
